name: Main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        version:  [ max ]
      fail-fast: false

    env:
      CODE_VERSION: ${{ matrix.version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Setup vsce
        run: |
            echo $PATH
            echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
            npm install --prefix=$HOME/.local -g vsce
            vsce --version

      - name: Download minikube (ubuntu)
        if: ${{ contains(matrix.os, 'ubuntu')
        run: |
            curl https://github.com/kubernetes/minikube/releases/latest/download/minikube-darwin-amd64
            echo "${HOME}/.local/bin" >> $GITHUB_PATH
            chmod +x minikube-darwin-amd64
            mv minikube-darwin-amd64 ${HOME}/.local/bin
      - name: Download minikube (macos)
        if: ${{ contains(matrix.os, 'macos')
        run: |
            curl https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
            echo "${HOME}/.local/bin" >> $GITHUB_PATH
            chmod +x minikube-linux-amd64
            mv minikube-linux-amd64 ${HOME}/.local/bin

      - name: Download minikube (windows)
        if: ${{ contains(matrix.os, 'windows')
        run: |
            curl https://github.com/kubernetes/minikube/releases/latest/download/minikube-windows-amd64.exe
            echo "${HOME}/.local/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
            chmod +x minikube-windows-amd64.exe
            mv minikube-windows-amd64.exe ${HOME}/.local/bin

      - name: Start minikube
        run: |
            minikube start